/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugListingsRouteImport } from './routes/$slug.listings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as SlugListingsListingIdRouteImport } from './routes/$slug.listings_.$listingId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardListingsListingIdRouteImport } from './routes/dashboard.listings_.$listingId'
import { Route as DashboardListingsNewRouteImport } from './routes/dashboard.listings_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugListingsRoute = SlugListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => SlugRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const SlugListingsListingIdRoute = SlugListingsListingIdRouteImport.update({
  id: '/listings_/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => SlugRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardListingsListingIdRoute =
  DashboardListingsListingIdRouteImport.update({
    id: '/listings_/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardListingsNewRoute = DashboardListingsNewRouteImport.update({
  id: '/listings_/new',
  path: '/listings/new',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$slug/listings': typeof SlugListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/$slug/': typeof SlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$slug/listings/$listingId': typeof SlugListingsListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/listings/$listingId': typeof DashboardListingsListingIdRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$slug/listings': typeof SlugListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/$slug': typeof SlugIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$slug/listings/$listingId': typeof SlugListingsListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/listings/$listingId': typeof DashboardListingsListingIdRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$slug/listings': typeof SlugListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/$slug/': typeof SlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$slug/listings_/$listingId': typeof SlugListingsListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/listings_/$listingId': typeof DashboardListingsListingIdRoute
  '/dashboard/listings_/new': typeof DashboardListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/$slug/listings'
    | '/admin/login'
    | '/dashboard/listings'
    | '/dashboard/profile'
    | '/$slug/'
    | '/dashboard/'
    | '/$slug/listings/$listingId'
    | '/api/auth/$'
    | '/dashboard/listings/$listingId'
    | '/dashboard/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/$slug/listings'
    | '/admin/login'
    | '/dashboard/listings'
    | '/dashboard/profile'
    | '/$slug'
    | '/dashboard'
    | '/$slug/listings/$listingId'
    | '/api/auth/$'
    | '/dashboard/listings/$listingId'
    | '/dashboard/listings/new'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/$slug/listings'
    | '/admin/login'
    | '/dashboard/listings'
    | '/dashboard/profile'
    | '/$slug/'
    | '/dashboard/'
    | '/$slug/listings_/$listingId'
    | '/api/auth/$'
    | '/dashboard/listings_/$listingId'
    | '/dashboard/listings_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/listings': {
      id: '/$slug/listings'
      path: '/listings'
      fullPath: '/$slug/listings'
      preLoaderRoute: typeof SlugListingsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/$slug/listings_/$listingId': {
      id: '/$slug/listings_/$listingId'
      path: '/listings/$listingId'
      fullPath: '/$slug/listings/$listingId'
      preLoaderRoute: typeof SlugListingsListingIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/listings_/$listingId': {
      id: '/dashboard/listings_/$listingId'
      path: '/listings/$listingId'
      fullPath: '/dashboard/listings/$listingId'
      preLoaderRoute: typeof DashboardListingsListingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings_/new': {
      id: '/dashboard/listings_/new'
      path: '/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof DashboardListingsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface SlugRouteChildren {
  SlugListingsRoute: typeof SlugListingsRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugListingsListingIdRoute: typeof SlugListingsListingIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugListingsRoute: SlugListingsRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugListingsListingIdRoute: SlugListingsListingIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardListingsListingIdRoute: typeof DashboardListingsListingIdRoute
  DashboardListingsNewRoute: typeof DashboardListingsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardListingsListingIdRoute: DashboardListingsListingIdRoute,
  DashboardListingsNewRoute: DashboardListingsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
